CC=g++ --std=c++11 -g

all: knapsack shopping

knapsack: knapsack.cpp
	$(CC) knapsack.cpp -o knapsack && ./knapsack

shopping: shopping.cpp
	$(CC) shopping.cpp -o shopping && ./shopping

clean:
	rm -f *.o knapsack shopping